### PR TITLE
Added the Enum name colum to Items and Enemies

### PR DESCRIPTION
**Pull request by Lyght-1**
Its really annoying having to search for the actual enum value. Some items/enemies have really different name in their respective enums.

### CODE REVIEW

**Review by aldelaro5 — CHANGES_REQUESTED** [review]
So this actually did reminded me of a consistency issue steming from my old docs: see, you shouldn't even see the English names in this.

Because the problem with putting the translated names is there's multiple languages, I would need to put all of them, but that information frankly isn't really practical for what I am aiming for with these docs: they should just document the internals stuff, but limit as much as possible to talk about their data content (in other words, I document the interface, but not the content). I also start to put too much imo, but that's a secondary issue.

I think these 2 are notable to have this issue, but what I should be doing is not have 3 columns, but 2 and one of them is the enum value, NOT the English name. The reality is looking up the names of everything shouldn't be the job of the docs, but a data scrapper which is something I been planning for quite a while in my head cause it's going to become very important and this is one of the reason (cause it's not practical to aggregate the data here, the README mentions why since the data can easily change or even be modded with, but the vanilla enum values are very unlikely to be messed with). This wouldn't just include the names btw, it would also be other metadata like description.

There is one exception to this that I realised: it's fine to mention the English names IF it provides clarifications on whatever I am documenting. This is something you'll see in ItemList and SetText docs because the game recalls specific common dialogue or menutext lines and putting the English lines clarifies what it is sometimes a lot better, but it's only for illustrative purposes only.

So I would be fine to merge this if you remove the English name column entirely and keep the enum value one with the same template then the AnimIDs page. There is some cleanups I wanted to do, this was one of them, another would be just better navigation with the SetText commands: they are kind of annoying to go through.

**Comment by Lyght-1** [comment]
So, the main reason i wanted to add the enum value besides the name is to clarify whatever the enum value actually represent. Cause it keeps happening where I want to have the value for an enemy, but the enum is vastly different from what the common name is. For example, the Numbnail is actually Snail in the enum for some reason so I have to go look it up everytime. 

In this case, I would just have to ctrl f for numbnail in here and it would just make it easier.

**Comment by aldelaro5** [comment]
> So, the main reason i wanted to add the enum value besides the name is to clarify whatever the enum value actually represent. Cause it keeps happening where I want to have the value for an enemy, but the enum is vastly different from what the common name is. For example, the Numbnail is actually Snail in the enum for some reason so I have to go look it up everytime.
> 
> In this case, I would just have to ctrl f for numbnail in here and it would just make it easier.

I understand the value on your side, but the reality is I have to deal with this for a lot more stuff and none of them specifically should be in these docs because it involves data processing and aggregation, not specs to do them.

Either I put everything in here or nothing because I want to at least be consistent, but i can't selectively put some with translated names and some not, same deal with anim ids, maps, boardquests and their bound flags, etc... If you saw a list of names which had an enum backing it, it is an error.

If you badly need this regardless before i end up doing a data scrapper to gather this and a lot more, my suggestion is to simply maintain your own fork internally. I say this because it sounds like you are dealing with very undocumented territories (BattleControl) which i won't even touch for a while. This means it's much more practical for you to do the data aggregation on a as needed basis before I go over and make a scrapper that obsoletes it.

**Comment by Lyght-1** [comment]
Alrighty I changed it to just have the enum values. And yeah i just made a spreadsheet for my own stuff with enums. 

Also, i have a question about game internals but i cant contact you anywhere so ill just post it here lmao : Do you know why Mar is doing a garbage collector in DoClock ? It seems to be reason behind the doaction transpiler weird stutter so...

**Review by aldelaro5 — CHANGES_REQUESTED** [review]
Please squash your commits, this can belong in one commit.

On the second point, sent a friend request on discord.

**Review by aldelaro5 — APPROVED** [review]
Nvm, I didn't know I can do the squash on my end.

**Comment by aldelaro5** [comment]
Update on this: during my effort to check BattleControl, I found out the medals not only had their English names, but that the enum backing them while not used in the code, was very likely originally used and the compiler optimised it out.

The problem is for historical reasons, the enum names doesn't match what ended up in game like quick flea is `SpeedUp` so it gets too confusing for even me to keep track which is kind of important because BattleControl is the biggest consumer of BadgeIsEquipped. This isn't the same for enemies or items because their names were usually very close, but medals are particularly bad for historical reasons.

So because of this and the fact the skills list also made me reconsider this (there's more problematic ones in it too), I will revise my decision and put the English name for convenience. I however will ONLY put the English one and it will strictly be for names where all elements of an enum has a clear one (so things like animids, I won't put a name because it gets very ambiguous)

However, I won't add these quite soon since not all of them is a priority, but at the very least, they will be done when I merge the BattleControl docs which is still 2-3 months off.

> > So, the main reason i wanted to add the enum value besides the name is to clarify whatever the enum value actually represent. Cause it keeps happening where I want to have the value for an enemy, but the enum is vastly different from what the common name is. For example, the Numbnail is actually Snail in the enum for some reason so I have to go look it up everytime.
> > In this case, I would just have to ctrl f for numbnail in here and it would just make it easier.
> 
> I understand the value on your side, but the reality is I have to deal with this for a lot more stuff and none of them specifically should be in these docs because it involves data processing and aggregation, not specs to do them.
> 
> Either I put everything in here or nothing because I want to at least be consistent, but i can't selectively put some with translated names and some not, same deal with anim ids, maps, boardquests and their bound flags, etc... If you saw a list of names which had an enum backing it, it is an error.
> 
> If you badly need this regardless before i end up doing a data scrapper to gather this and a lot more, my suggestion is to simply maintain your own fork internally. I say this because it sounds like you are dealing with very undocumented territories (BattleControl) which i won't even touch for a while. This means it's much more practical for you to do the data aggregation on a as needed basis before I go over and make a scrapper that obsoletes it.

**Pull request merged**
